import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const [userInput, setUserInput] = useState<string>('');
  const [hashtags, setHashtags] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const fetchHashtags = async () => {
    setIsLoading(true);
    const response = await fetch(
      `https://jilog4h5k7.execute-api.eu-west-3.amazonaws.com/prod/getHashtags?userInput=${encodeURIComponent(
        userInput
      )}`
    );
    const data = await response.json();
    setHashtags(data.hashtags);
    setIsLoading(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(hashtags);
  };

  return (
    <>
      <Head>
        <title>HashTag Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Hashtags Generator</h1>
          <input
            type="text"
            value={userInput}
            onChange={(e) => setUserInput(e.target.value)}
            placeholder="Enter your input"
          />
          <button onClick={fetchHashtags} disabled={isLoading}>
            Envoyer
          </button>
          {isLoading && <p>Loading...</p>}
          <div>
            <h2>Hashtags</h2>
            <pre>{hashtags}</pre>
            {hashtags && (
              <button onClick={copyToClipboard}>Copy to clipboard</button>
            )}
          </div>
        </div>
      </main>
    </>
  )
}
